---
Resources:
  AppTabAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/AppTabKey
      TargetKeyId:
        Ref: AppTabKMS
  AppTabKMS:
    Type: AWS::KMS::Key
    Properties:
      Description: AppTab kms key
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                - ''
                - - 'arn:aws:iam::'
                  - Ref: AWS::AccountId
                  - ":role/apptab-web-api-dev-us-west-2-lambdaRole"
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: "*"
          - Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                - ''
                - - 'arn:aws:iam::'
                  - Ref: AWS::AccountId
                  - ":root"
            Action:
              - kms:Create*
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: "*"
Outputs:
  AppTabKMSArn:
    Value: !GetAtt AppTabKMS.Arn
    Export:
      Name: AppTabKMSArn
  AppTabKMSId:
    Value: Ref AppTabKMS
    Export:
      Name: AppTabKMSId