---
Description: Cognito pools for apptab
Resources:
  DevCustomerPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AliasAttributes:
        - phone_number
      MfaConfiguration: "OFF"
      UserPoolName: AppTabDevCustomerPool
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: True
          Required: True
          StringAttributeConstraints:
            MaxLength: 11
            MinLength: 2
        - Name: phone_number
          AttributeDataType: String
          Mutable: False
          Required: True
          StringAttributeConstraints:
            MaxLength: 10
            MinLength: 10
      SmsAuthenticationMessage: "AppTab authentication code: {####}"
      SmsVerificationMessage: "AppTab authentication code: {####}"
  DevClientPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AliasAttributes:
        - email
      MfaConfiguration: "OFF"
      UserPoolName: AppTabDevClientPool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: True
          Required: True
        - Name: phone_number
          AttributeDataType: String
          Mutable: True
          Required: True
          StringAttributeConstraints:
            MaxLength: 10
            MinLength: 10
  ProdCustomerPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AliasAttributes:
        - phone_number
      MfaConfiguration: "OFF"
      UserPoolName: AppTabProdCustomerPool
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: True
          Required: True
          StringAttributeConstraints:
            MaxLength: 11
            MinLength: 2
        - Name: phone_number
          AttributeDataType: String
          Mutable: False
          Required: True
          StringAttributeConstraints:
            MaxLength: 10
            MinLength: 10
  ProdClientPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AliasAttributes:
        - email
      MfaConfiguration: "OFF"
      UserPoolName: AppTabProdClientPool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: True
          Required: True
        - Name: phone_number
          AttributeDataType: String
          Mutable: True
          Required: True
          StringAttributeConstraints:
            MaxLength: 10
            MinLength: 10
  DevCustomerPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AppTabCustomerAppDev
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: False
      UserPoolId:
        Ref: DevCustomerPool
  DevClientPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AppTabClientAppDev
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: False
      UserPoolId:
        Ref: DevClientPool
  ProdCustomerPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AppTabCustomerAppProd
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: False
      UserPoolId:
        Ref: ProdCustomerPool
  ProdClientPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AppTabClientAppProd
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: False
      UserPoolId:
        Ref: ProdClientPool
Outputs:
  devCustomerPool:
    Value:
      Ref: DevCustomerPool
    Export:
      Name: devCustomerPool
  devCustomerPoolClient:
    Value:
      Ref: DevCustomerPoolClient
    Export:
      Name: devCustomerPoolClient
  devClientPool:
    Value:
      Ref: DevClientPool
    Export:
      Name: devClientPool
  devClientPoolCleint:
    Value:
      Ref: DevClientPoolClient
    Export:
      Name: devClientPoolCleint
  prodCustomerPool:
    Value:
      Ref: ProdCustomerPool
    Export:
      Name: prodCustomerPool
  prodCustomerPoolClient:
    Value:
      Ref: ProdCustomerPoolClient
    Export:
      Name: prodCustomerPoolClient
  prodClientPool:
    Value:
      Ref: ProdClientPool
    Export:
      Name: prodClientPool
  prodClientPoolClient:
    Value:
      Ref: ProdClientPoolClient
    Export:
      Name: prodClientPoolClient
