service: apptab-backend
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.default_stage}
  memorySize: 128
  environment:
    stage: ${self:provider.stage}
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "*"
      Resource: "arn:aws:s3:::${self:provider.stage}-apptab-formatted-data-bucket"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

custom:
  default_stage: dev

package:
  include:
    - dist/**
  exclude:
    - lib/**
    - package.json
    - package-lock.json
    - typings/**
    - test/**
    - request_templates/**
    - .git
    - .gitignore
    - .babelrc
    - .npmignore
    - tsconfig.json
    - typings.json
    - typings/**
    - webpack.config.js
    - .idea/**
    - node_modules/**

functions:
  processFirehoseData:
    handler: dist/processFirehoseData.processFirehoseData

resources:
  Resources:
    NodeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: NodeId
          AttributeType: S
        - AttributeName: VenueId
          AttributeType: S
        KeySchema:
        - AttributeName: NodeId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        TableName: ${self:provider.stage}-NodeTable
        GlobalSecondaryIndexes:
        - IndexName: VenueIdToNodeId
          KeySchema:
          - AttributeName: VenueId
            KeyType: HASH
          - AttributeName: NodeId
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '1'
            WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: VenueId
          AttributeType: S
        - AttributeName: ItemId
          AttributeType: S
        TableName: ${self:provider.stage}-MenuTable
        KeySchema:
        - AttributeName: VenueId
          KeyType: HASH
        - AttributeName: ItemId
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    VenueTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: VenueId
          AttributeType: S
        - AttributeName: VenueName
          AttributeType: S
        - AttributeName: CreatorClientId
          AttributeType: S
        TableName: ${self:provider.stage}-VenueTable
        KeySchema:
        - AttributeName: VenueId
          KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: NameToId
          KeySchema:
          - AttributeName: VenueName
            KeyType: HASH
          - AttributeName: VenueId
            KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: '1'
            WriteCapacityUnits: '1'
        - IndexName: ClientIdToVenueId
          KeySchema:
          - AttributeName: CreatorClientId
            KeyType: HASH
          - AttributeName: VenueId
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '1'
            WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    ClientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: ClientId
          AttributeType: S
        TableName: ${self:provider.stage}-ClientTable
        KeySchema:
        - AttributeName: ClientId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    SubscriptionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: ClientId
          AttributeType: S
        - AttributeName: NodeId
          AttributeType: S
        TableName: ${self:provider.stage}-SubscriptionTable
        KeySchema:
        - AttributeName: NodeId
          KeyType: HASH
        - AttributeName: ClientId
          KeyType: RANGE
        GlobalSecondaryIndexes:
        - IndexName: ClientIdToNodeId
          KeySchema:
          - AttributeName: ClientId
            KeyType: HASH
          - AttributeName: NodeId
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '1'
            WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-CustomerTable
        AttributeDefinitions:
        - AttributeName: CustomerId
          AttributeType: S
        KeySchema:
        - AttributeName: CustomerId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    CardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-CardTable
        AttributeDefinitions:
        - AttributeName: CardId
          AttributeType: S
        - AttributeName: CustomerId
          AttributeType: S
        KeySchema:
        - AttributeName: CustomerId
          KeyType: HASH
        - AttributeName: CardId
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    TransactionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-TransactionTable
        AttributeDefinitions:
          - AttributeName: TransactionId
            AttributeType: S
          - AttributeName: CustomerId
            AttributeType: S
          - AttributeName: ClientId
            AttributeType: S
        KeySchema:
          - AttributeName: TransactionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
        - IndexName: ClientKey
          KeySchema:
          - AttributeName: ClientId
            KeyType: HASH
          - AttributeName: TransactionId
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: CustomerKey
          KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH
          - AttributeName: TransactionId
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    CustomerPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: False
        AliasAttributes:
          - phone_number
        MfaConfiguration: "OFF"
        UserPoolName: ${self:provider.stage}-CustomerPool
        Schema:
          - Name: name
            AttributeDataType: String
            Mutable: True
            Required: True
            StringAttributeConstraints:
              MaxLength: 11
              MinLength: 2
          - Name: phone_number
            AttributeDataType: String
            Mutable: False
            Required: True
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 12
        SmsAuthenticationMessage: "AppTab authentication code: {####}"
        SmsVerificationMessage: "AppTab authentication code: {####}"
    ClientPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: False
        AliasAttributes:
          - email
        MfaConfiguration: "OFF"
        UserPoolName: ${self:provider.stage}-ClientPool
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: True
            Required: True
          - Name: phone_number
            AttributeDataType: String
            Mutable: True
            Required: True
            StringAttributeConstraints:
              MaxLength: 20
              MinLength: 12
    CustomerPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-CustomerApp
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: False
        UserPoolId:
          Ref: CustomerPool
    ClientPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-ClientApp
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: False
        UserPoolId:
          Ref: ClientPool
    FirehoseRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
        Policies:
        - PolicyName: FirehoseToS3WritePolicy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action: logs:PutLogEvents
              Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:logs:'
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":log-group:"
                  - Ref: FirehoseLogGroup
                  - ":log-stream:"
                  - Ref: FirehoseLogs
            - Effect: Allow:
              Action:
              - lambda:Invoke
              Resource:
                Fn::Join:
                - ""
                - - "arn:aws:lambda:${self:provider.region}:"
                  - Ref: "AWS::AccountId"
                  - ":function:${self:service}-${self:provider.stage}-processFirehoseData"
            - Effect: Allow
              Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
              Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: DataBucket
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: DataBucket
                  - "/*"
    FirehoseLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: ${self:provider.stage}-AppTabFirehoseLogs
        RetentionInDays: 3
    FirehoseLogs:
      Type: AWS::Logs::LogStream
      Properties:
        LogStreamName: ${self:provider.stage}-AppTabFirehoseLogStream
        LogGroupName:
          Ref: FirehoseLogGroup
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-apptab-data-bucket
    FormattedDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-apptab-formatted-data-bucket
    Firehose:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamName: ${self:provider.stage}-apptab-data-stream
        ExtendedS3DestinationConfiguration:
          BucketARN:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: DataBucket
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 10
          RoleARN:
            Fn::GetAtt:
            - FirehoseRole
            - Arn
          CompressionFormat: ZIP
          ProcessingConfiguraiton:
            Enabled: true
            Processors:
            - Parameters:
                - ParameterName: LambdaArn
                  ParameterValue:
                    Fn::Join:
                    - ""
                    - - "arn:aws:lambda:${self:provider.region}:"
                      - Ref: "AWS::AccountId"
                      - ":function:${self:service}-${self:provider.stage}-processFirehoseData"
              Type: Lambda
          Prefix: apptab
          CloudWatchLoggingOptions:
            Enabled: true
            LogGroupName:
              Ref: FirehoseLogGroup
            LogStreamName:
              Ref: FirehoseLogs
    FirehoseWriteIDP:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${self:provider.stage}CustomerIDP
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
        - ClientId:
            Ref: CustomerPoolClient
          ProviderName:
            Fn::GetAtt:
            - CustomerPool
            - ProviderName
          ServerSideTokenCheck: true
    FirehoseWriteIDPRole:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: FirehoseWriteIDP
        Roles:
          authenticated:
            Fn::GetAtt:
            - FirehoseWriteRole
            - Arn
          unauthenticated:
            Fn::GetAtt:
            - FirehoseWriteRole
            - Arn
    FirehoseWriteRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
            - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud":
                  Ref: FirehoseWriteIDP
        Policies:
        - PolicyName: WriteToFirehose
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
              - firehose:PutRecord
              - firehose:PutRecordBatch
              Resource:
              - Fn::Join:
                - ""
                - - "arn:aws:firehose:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":deliverystream/"
                  - Ref: Firehose
    ClosedTransactionBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-apptab-closed-transaction-bucket
  Outputs:
    SubscriptionTable:
      Value:
        Ref: SubscriptionTable
      Export:
        Name: ${self:provider.stage}-SubscriptionTable
    NodeTable:
      Value:
        Ref: NodeTable
      Export:
        Name: ${self:provider.stage}-NodeTable
    MenuTable:
      Value:
        Ref: MenuTable
      Export:
        Name: ${self:provider.stage}-MenuTable
    VenueTable:
      Value:
        Ref: VenueTable
      Export:
        Name: ${self:provider.stage}-VenueTable
    CardTable:
      Value:
        Ref: CardTable
      Export:
        Name: ${self:provider.stage}-CardTable
    ClientTable:
      Value:
        Ref: ClientTable
      Export:
        Name: ${self:provider.stage}-ClientTable
    CustomerTable:
      Value:
        Ref: CustomerTable
      Export:
        Name: ${self:provider.stage}-CustomerTable
    TransactionTable:
      Value:
        Ref: TransactionTable
      Export:
        Name: ${self:provider.stage}-TransactionTable
    CustomerPool:
      Value:
        Ref: CustomerPool
      Export:
        Name: ${self:provider.stage}-CustomerPool
    CustomerPoolClient:
      Value:
        Ref: CustomerPoolClient
      Export:
        Name: ${self:provider.stage}-CustomerPoolClient
    CustomerPoolArn:
      Value:
        Fn::GetAtt: [CustomerPool, Arn]
      Export:
        Name: ${self:provider.stage}-CustomerPoolArn
    ClientPool:
      Value:
        Ref: ClientPool
      Export:
        Name: ${self:provider.stage}-ClientPool
    ClientPoolClient:
      Value:
        Ref: ClientPoolClient
      Export:
        Name: ${self:provider.stage}-ClientPoolClient
    ClientPoolArn:
      Value:
        Fn::GetAtt: [ClientPool, Arn]
      Export:
        Name: ${self:provider.stage}-ClientPoolArn
    ClosedTransactionBucket:
      Value:
        Fn::GetAtt: [ClosedTransactionBucket, Arn]
      Export:
        Name: ${self:provider.stage}-ClosedTransactionBucket
